import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "./src/generated/schema.graphql",
  documents: "./src/queries/**/*.graphql",
  config: {
    scalars: {
      UUID: "string",
      Username: "string",
      Url: "string",
      Tag: "string",
      Datetime: "string",
      BigInt: "string",
    },
  },
  generates: {
    "./src/generated/index.ts": {
      plugins: [
        {
          add: {
            content: [
              "/* WARNING: This file is automatically generated. Do not edit. */",
            ],
          },
        },
        "typescript",
        "typescript-operations",
        // "typescript-resolvers",
        "typescript-react-apollo",
        // "typed-document-node",
      ],
      config: {
        immutableTypes: true,
        enumsAsTypes: true,
        namingConvention: "change-case#pascalCase",
        noGraphQLTag: false,
        overwrite: true,
        skipTypename: true,
        withComponent: false,
        withHOC: false,
        withHooks: true,
        withMutationFn: true,
      },
    },
  },
  hooks: {
    afterOneFileWrite: ["prettier --write './src/generated/index.ts'"],
  },
};
export default config;
