import { CodegenConfig } from "@graphql-codegen/cli";
import graphqlconfig from './graphql.config.js'

const config: CodegenConfig = {
  ...graphqlconfig,
  config: {
    scalars: {
      UUID: "string",
      Username: "string",
      Url: "string",
      Tag: "string",
      Datetime: "string",
      BigInt: "string",
    },
  },
  generates: {
    // "./src/generated/": {
    //   preset: 'client',
    "./app/generated/index.ts": {
      plugins: [
        {
          add: {
            content: [
              "/* WARNING: This file is automatically generated. Do not edit. */",
            ],
          },
        },
        "typescript",
        "typescript-operations",
        // "typescript-react-apollo",
        "typed-document-node",
      ],
      config: {
        immutableTypes: true,
        enumsAsTypes: true,
        namingConvention: "change-case#pascalCase",
        noGraphQLTag: false,
        overwrite: true,
        skipTypename: true,
        withComponent: false,
        withHOC: false,
        withHooks: true,
        withMutationFn: true,
      },
    },
  },
  hooks: {
    afterOneFileWrite: ["prettier --write './app/generated/index.ts'"],
  },
};
export default config;
